// lib/colors.ts
export const SPORT_COLORS: Record<string, string> = {
  corrida: "blue",
  futevolei: "orange",
  volei_praia: "yellow",
  beach_tennis: "purple",
  frescobol: "green",
  surf: "teal",
  sup: "deepskyblue",
  canoagem: "brown",
  futebol: "darkgreen",
  tenis: "navy",
  bike: "darkorange",
  slackline: "limegreen",
  skate: "gray",
  funcional: "red",
  yoga: "violet",
  pilates: "pink",
  meditacao: "lightseagreen",
  danca: "hotpink",
  capoeira: "gold",
  tecido: "indigo",
  natacao: "aqua",
};
